apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: dbgate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
          env:
            - name: DBGATE_PORT
              value: "{{ .Values.service.port }}"
          volumeMounts:
            - name: config
              mountPath: /app/dbgate.yaml
              subPath: dbgate.yaml
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-config
