image:
  repository: nathanfirmo/dbgate
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9999
  nodePort: null

config:
  databases:
    - name: platform
      type: mysql
      dsn: root:mysqlroot@tcp(127.0.0.1:3306)/platform
    - name: notifications
      type: mongo
      uri: mongodb://127.0.0.1:27017
      database: notifications
